version: "3"
services:
  app:
    container_name: node-app
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
